apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  labels:
    app: user-service
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: user-service