apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  host: "postgres-service"
  username: "postgres_user"
  password: "postgres_password"
  database: "user_service_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  url: "amqp://rabbit_user:rabbit_password@rabbitmq-service:5672"